server:
  port: 8884

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: http://localhost:8081
              predicates:
                - Path=/users/**
            - id: HOTEL-SERVICE
              uri: lb://HOTELSERVICE
              predicates:
                - Path=/hotels/**,/staffs/**

            - id: RATING-SERVICE
              uri: lb://RATINGSERVICE
              predicates:
                - Path=/ratings/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service_url:
      defaultZone: http://localhost:8761/eureka
